apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab4-webapp
spec:
  selector:
    matchLabels:
      app: lab4-webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: lab4-webapp
    spec:
      containers:
        - name: lab4-webapp
          image: docker.io/joker759/jotterapi:latest
          ports:
            - containerPort: 5000
              name: "http"
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PASSWORD
            - name: ConnectionStrings__JotterDbContext
              value: User ID=$(POSTGRES_USER);Password=$(POSTGRES_PASSWORD);Host=$(POSTGRES_SERVICE_HOST);Port=5432;Database=$(POSTGRES_DB);Pooling=true;
          resources:
            limits:
              memory: 2Gi
              cpu: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: lab4-webapp
spec:
  selector:
    app: lab4-webapp
  ports:
    - name: "http"
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30103
  type: NodePort
