apiVersion: v1
kind: PersistentVolume
metadata:
  name: lab4-pv
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce  
  hostPath:
    path: postgresdata
    
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab4-pvc
  labels:
    app: postgres
spec:
  volumeName: lab4-pv
  storageClassName: manual
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13 
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432 
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: lab4-pvc
      
---

apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: "postgres"
      protocol: TCP
      port: 5432
      targetPort: 5432
